# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
Your Code
'''


'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [5]:
A = np.random.random((5, 5))

'''
Your Code
'''
A

array([[0.71784364, 0.47859251, 0.83818479, 0.56133216, 0.60220291],
       [0.76691792, 0.01788906, 0.8338094 , 0.05504995, 0.32540613],
       [0.42947039, 0.33657779, 0.33323754, 0.63955687, 0.66313059],
       [0.20252208, 0.18536716, 0.91376829, 0.17260684, 0.63923506],
       [0.12235724, 0.56101635, 0.59255406, 0.42593932, 0.54444234]])

In [8]:
(A - A.mean()) / A.std()

array([[ 9.58221879e-01,  9.28658722e-04,  1.43973171e+00,
         3.31987100e-01,  4.95519412e-01],
       [ 1.15457821e+00, -1.84244109e+00,  1.42222488e+00,
        -1.69375266e+00, -6.12001726e-01],
       [-1.95619101e-01, -5.67301597e-01, -5.80666615e-01,
         6.44980344e-01,  7.39303655e-01],
       [-1.10368620e+00, -1.17232659e+00,  1.74215692e+00,
        -1.22338327e+00,  6.43692720e-01],
       [-1.42444228e+00,  3.30723483e-01,  4.56912393e-01,
        -2.09747641e-01,  2.64407425e-01]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [16]:
a = np.arange(11)
a[a.argmax()] = -1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1])